---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-deployment
spec:
  replicas: 4
  template:
    spec:
      containers:
      - name: webserver-simple
        env:
        - name: ENV
          value: "staging"
        - name: GPU_ENABLED
          value: "1"
      
