---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-deployment
spec:
  template:
    spec:
      containers:
      - name: webserver-simple
        env:
        - name: ENV
          value: "staging"  # Definindo o valor da variável "ENV" como "staging"
        - name: GPU_ENABLED # Definindo uma variável de ambiente chamada "GPU_ENABLED"
          value: "1"        # Definindo o valor da variável "GPU_ENABLED" como "1"
      
