
apiVersion: v1
kind: Service
metadata:
  name: simple-service
spec:
  type: LoadBalancer
  selector:
    app: trivial-go-web-app
  ports:
      - nodePort: 31007
        protocol: TCP
        port: 8080
        name: staging-port