---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-deployment
spec:
  template:
    spec:
      containers:
      - name: webserver-simple # Nome do container dentro do pod
        image: docker.io/kostiscodefresh/simple-env-app:1.0 # Especificando a imagem do container a ser usada